### ISSUE TITLE
#1 : User can search breed of dog

### ISSUE THREAD

**Issue by AngelaJiaNan** [AngelaJiaNan/ajax-project#1]
## ⚙️ Feature

> user can search and select on breed of their choice.

## 📐 Functionality

>The user will be able to search and see breed data.

## 🖼️ Wireframes
![Screen Shot 2021-11-08 at 4 06 04 PM](https://user-images.githubusercontent.com/90875226/140837694-c15896c6-f003-4321-9c54-4819539eefcd.png)

![Screen Shot 2021-11-08 at 4 07 10 PM](https://user-images.githubusercontent.com/90875226/140837757-01433fba-4ab8-4e7e-bcc1-2434b2f13bf7.png)

## ✅ Task List
- [x] Add a div[data-view="search-form"] to the HTML.
- [x] Add search drop down bar to the div [data-view="search-form"]
- [x] Make Ajaxs request to get all the data for all the breeds.
- [x] Make sure all breeds are loaded into search bar.
- [x] add  div[data-view ="breed-data"] to the HTML.
- [x] ensure that when breed is selected: the breed's image & data shows up.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
