### ISSUE TITLE
#2 Feature: User can add breeds to favorite list

### ISSUE THREAD

**Issue by AngelaJiaNan** [AngelaJiaNan/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![Screen Shot 2021-11-08 at 5 14 24 PM](https://user-images.githubusercontent.com/90875226/140843613-5cdaae4d-b147-41a2-9c86-78bfa7b1069a.png)

![Screen Shot 2021-11-08 at 5 13 48 PM](https://user-images.githubusercontent.com/90875226/140843559-aba4e66f-6c4b-48c6-a452-e45dec9189a7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add add to favorite button on breed information page
- [x] add event listener to favorite button
- [x] add div data-view= favorite list on HTML 
- [x] ensure that added favorite breed onto the page 
- [x] verify that breed being added are saved to local storage
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
- [x] check to make sure on desktop view & moblie view
