### ISSUE TITLE
#3 Feature: User can edit & delete items on list  

### ISSUE THREAD

**Issue by AngelaJiaNan** [AngelaJiaNan/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![Screen Shot 2021-11-08 at 5 19 08 PM](https://user-images.githubusercontent.com/90875226/140844062-87793ff3-8513-4258-88e5-3c5a4ca778fe.png)

![Screen Shot 2021-11-08 at 5 18 33 PM](https://user-images.githubusercontent.com/90875226/140844005-6695dda7-91b0-4a14-8f6b-141683655c9f.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add delete btn 
- [x] made the modal 
- [x] make sure when clicked no the modal hides and goes back to the favorite breed list
- [x] when clicked yes, make sure the breed is deleted
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
