### ISSUE TITLE
#4 Feature: User can add comments 

### ISSUE THREAD

**Issue by AngelaJiaNan** [AngelaJiaNan/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![Screen Shot 2021-11-08 at 5 17 14 PM](https://user-images.githubusercontent.com/90875226/140844234-1b070b8d-e370-4450-9024-8fb0734a1954.png)

![Screen Shot 2021-11-08 at 5 21 18 PM](https://user-images.githubusercontent.com/90875226/140844290-97ed9a6d-fe8a-4e23-af50-a8b9264d2478.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add submit BTN for add comment 
- [ ] make comment box 
- [ ] when user clicks on submit, comment should appear on the fav list 
- [ ] when user clicks cancel, page should go back to the fav-breeds list and comment box hide
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
